export const HungarianWords: Record<string, string> = {
	pencil: 'Ceruza',
	eraser: 'Radír',
	clear: 'Törlés',
	home: 'Főoldal',
	normalPlay: 'Normál játék',
	freePlay: 'Szabad játék',
	helper: 'Súgó',
	words: 'Szavak',
	yourFinalScoreIs: 'A végső pontszámod:',
	playAnother: 'Szeretnél új játékot kezdeni?',
	yes: 'Igen',
	no: 'Nem',
	score: 'Pontok',
	yourWord: 'A szavad',
	myGuessWas: 'Én erre a szóra tippeltem:',
	submit: 'Kész',
	iThinkItis: 'Szerintem ez egy',
	settings: 'Beállítások',
	start: 'Kezdés',
	typeYourName: 'Írd be a nevedet',
	yourName: 'A neved',
}

export const EnglishWords: Record<string, string> = {
	pencil: 'Pencil',
	eraser: 'Eraser',
	clear: 'Clear',
	home: 'Home',
	normalPlay: 'Normal play',
	freePlay: 'Free play',
	helper: 'Helper',
	words: 'Words',
	yourFinalScoreIs: 'Your final score:',
	playAnother: 'Would you like to play another?',
	yes: 'Yes',
	no: 'No',
	score: 'Score',
	yourWord: 'Your word',
	myGuessWas: 'My guess was:',
	submit: 'Submit',
	iThinkItis: 'I think it is',
	settings: 'Settings',
	start: 'Start',
	typeYourName: 'Type your name',
	yourName: 'Your name',
}
