export const categories = [
	{ word: 'piano', word_id: 5 },
	{ word: 'pineapple', word_id: 8 },
	{ word: 'clock', word_id: 1 },
	{ word: 'swing set', word_id: 7 },
	{ word: 'sun', word_id: 17 },
	{ word: 'bucket', word_id: 2 },
	{ word: 'sailboat', word_id: 18 },
	{ word: 'skateboard', word_id: 6 },
	{ word: 'rainbow', word_id: 0 },
	{ word: 'ice cream', word_id: 10 },
	{ word: 'umbrella', word_id: 11 },
	{ word: 'ladder', word_id: 15 },
	{ word: 'bicycle', word_id: 19 },
	{ word: 'pear', word_id: 3 },
	{ word: 'bread', word_id: 14 },
	{ word: 'house', word_id: 4 },
	{ word: 'butterfly', word_id: 13 },
	{ word: 'strawberry', word_id: 16 },
	{ word: 'snowflake', word_id: 12 },
	{ word: 'donut', word_id: 9 },
]
